# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    # Overall project coverage
    project:
      default:
        target: auto
        threshold: 1%  # Allow 1% drop in overall coverage

    # Patch coverage (new code in PR)
    patch:
      default:
        target: 50%  # Require 50% coverage for new code (lowered from default 70%)
        threshold: 10%  # Allow larger variance for now

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # Always comment, even if no coverage changes
